<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ListMovies.aspx.cs" Inherits="ShereYourMovies.ListMovies" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="FeaturedContent" runat="server">
    <label id="lblDebug" runat="server"></label>
    <h1 id="husername" runat="server"></h1>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="grdElokuvat" runat="server"
        AutoGenerateColumns="false" 
        AutoGenerateEditButton="true" 
        AutoGenerateDeleteButton="true"
        AutoGenerateSelectButton="true"
        AllowSorting="true"
        AllowPaging="true"

        OnSorting="grdElokuvat_Sorting"
        OnSelectedIndexChanging="grdElokuvat_SelectedIndexChanging"
        OnPageIndexChanging="grdElokuvat_PageIndexChanging" 
        OnRowCancelingEdit="grdElokuvat_RowCancelingEdit" 
        OnRowDeleting="grdElokuvat_RowDeleting" 
        OnRowEditing="grdElokuvat_RowEditing" 
        OnRowUpdating="grdElokuvat_RowUpdating"

        BackColor="LightGoldenrodYellow" 
        BorderColor="Tan" 
        BorderWidth="1px" 
        CellPadding="2" 
        ForeColor="Black" 
        GridLines="None">
        <AlternatingRowStyle BackColor="PaleGoldenrod" />
        <FooterStyle BackColor="Tan" />
        <HeaderStyle BackColor="Tan" Font-Bold="True" />
        <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
        <SortedAscendingCellStyle BackColor="#FAFAE7" />
        <SortedAscendingHeaderStyle BackColor="#DAC09E" />
        <SortedDescendingCellStyle BackColor="#E1DB9C" />
        <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        <Columns>
            <asp:BoundField DataField="Nimi" HeaderText="Nimi" SortExpression="Nimi" />
            <asp:BoundField DataField="Tahdet" HeaderText="Tähdet" SortExpression="Tahdet" />
        </Columns>
    </asp:GridView>
</asp:Content>
